// Auto-generated by Style Dictionary — do not edit manually.

export const colors = {
  textPrimary: 'var(--colors-textPrimary)',
  textSecondary: 'var(--colors-textSecondary)',
  textTertiary: 'var(--colors-textTertiary)',
  textMuted: 'var(--colors-textMuted)',
  textDisabled: 'var(--colors-textDisabled)',
  white: 'var(--colors-white)',
  surface: 'var(--colors-surface)',
  textInverse: 'var(--colors-textInverse)',
  bgPage: 'var(--colors-bgPage)',
  bgSubtle: 'var(--colors-bgSubtle)',
  bgInfo: 'var(--colors-bgInfo)',
  bgSuccess: 'var(--colors-bgSuccess)',
  bgWarning: 'var(--colors-bgWarning)',
  bgError: 'var(--colors-bgError)',
  bgOrangeLight: 'var(--colors-bgOrangeLight)',
  borderLight: 'var(--colors-borderLight)',
  borderDefault: 'var(--colors-borderDefault)',
  borderMedium: 'var(--colors-borderMedium)',
  brand: 'var(--colors-brand)',
  brandLight: 'var(--colors-brandLight)',
  brandBg: 'var(--colors-brandBg)',
  brandDark: 'var(--colors-brandDark)',
  brandDeep: 'var(--colors-brandDeep)',
  brandAccent: 'var(--colors-brandAccent)',
  navy900: 'var(--colors-navy900)',
  navy700: 'var(--colors-navy700)',
  navy50: 'var(--colors-navy50)',
  success: 'var(--colors-success)',
  successBorder: 'var(--colors-successBorder)',
  warning: 'var(--colors-warning)',
  warningBorder: 'var(--colors-warningBorder)',
  error: 'var(--colors-error)',
  iceExcellent: 'var(--colors-iceExcellent)',
  iceGood: 'var(--colors-iceGood)',
  iceFair: 'var(--colors-iceFair)',
  icePoor: 'var(--colors-icePoor)',
  iceNodata: 'var(--colors-iceNodata)',
  amber: 'var(--colors-amber)',
  amber400: 'var(--colors-amber400)',
  amberDark: 'var(--colors-amberDark)',
  amberBorder: 'var(--colors-amberBorder)',
  orangeDeep: 'var(--colors-orangeDeep)',
  purple: 'var(--colors-purple)',
  purpleBg: 'var(--colors-purpleBg)',
  purpleBorder: 'var(--colors-purpleBorder)',
  indigoBg: 'var(--colors-indigoBg)',
  indigoBorder: 'var(--colors-indigoBorder)',
  indigo: 'var(--colors-indigo)',
  stone50: 'var(--colors-stone50)',
  stone200: 'var(--colors-stone200)',
  stone300: 'var(--colors-stone300)',
  stone400: 'var(--colors-stone400)',
  stone500: 'var(--colors-stone500)',
  stone700: 'var(--colors-stone700)',
  stone800: 'var(--colors-stone800)',
  stone950: 'var(--colors-stone950)',
  heroBg: 'var(--colors-heroBg)',
  heroMid: 'var(--colors-heroMid)',
  heroLight: 'var(--colors-heroLight)',
} as const;

export const text = {
  '2xs': 10,
  xs: 11,
  sm: 12,
  md: 13,
  base: 14,
  lg: 15,
  xl: 18,
  '2xl': 24,
} as const;

export const radius = {
  sm: 6,
  md: 8,
  lg: 10,
  xl: 12,
  '2xl': 14,
  '3xl': 16,
  full: '50%',
} as const;

export const layout = {
  maxWidthNarrow: 560,
  maxWidthDefault: 680,
  maxWidthWide: 720,
  maxWidthFull: 1100,
  maxWidth5xl: 1024,
  navPadding: '14px 24px',
} as const;

export const shadow = {
  sm: 'var(--shadow-sm)',
  md: 'var(--shadow-md)',
  lg: 'var(--shadow-lg)',
  xl: 'var(--shadow-xl)',
  focus: 'var(--shadow-focus)',
} as const;

export const transition = {
  fast: 'all 0.15s ease',
  normal: 'all 0.2s ease',
} as const;

export const nav = {
  bg: 'var(--nav-bg)',
  blur: 'blur(12px)',
} as const;
